name: Flat Data Lassa Reports Fetcher

on:
  workflow_dispatch:  # Allow manual triggering only for testing

jobs:
  fetch-lassa-data:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch NCDC Lassa reports page
      - name: Fetch NCDC Lassa reports page
        uses: githubocto/flat@v3
        with:
          http_url: https://ncdc.gov.ng/diseases/sitreps/?cat=5&name=An%20update%20of%20Lassa%20fever%20outbreak%20in%20Nigeria
          downloaded_filename: data/raw/ncdc_lassa_page.html