name: Lassa Reports Scraping Pipeline

on:
  schedule:
    # Run every Monday at 1:00 AM UTC
    - cron: '0 1 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Create data directories
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
        mkdir -p data/documentation
        
    - name: Run Lassa Reports Scraping Pipeline
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
        B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
      run: python main.py
